# Generated by Django 3.2 on 2022-02-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='level',
            field=models.CharField(choices=[('jss1', 'jss1'), ('jss2', 'jss2'), ('jss3', 'jss3'), ('sss1', 'sss1'), ('sss2', 'sss2'), ('sss3', 'sss3')], default='jss1', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=10),
        ),
    ]
