# Generated by Django 3.2 on 2022-02-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20220203_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
