# Generated by Django 3.2 on 2022-02-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='bio',
        ),
    ]
