# Generated by Django 3.2 on 2022-02-05 18:39

import ckeditor.fields
import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_auto_20220204_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Standard',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='standard',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
